컴뱃 오더스 적용 (진행중)
oleneyl/maplestory_dpm_calc pull request #303
Opened 2020-08-27 13:31 UTC by cheese98

#270

알파벳순으로 진행중입니다. 다른 직업들도 완성되는대로 업데이트하도록 하겠습니다.

완료 직업
* 엔젤릭버스터

2020-08-27 19:23 UTC, icepeng commented
어빌리티에 패시브 레벨 +1을 쓰지 않는 직업이라도 수치 자체는 넣어두는게 좋습니다. 레벨당 수치는 위컴알 보거나, 일본 dpm 시트에 잘 되어있으니 참고하면 됩니다.

2020-08-28 12:02 UTC, cheese98 commented
아란, 배틀메이지 해서 올립니다. 모법은 나중에 한번에 처리하려고 미뤘고, 아크는 다른 분께서 PR 중이시길래 스킵했습니다.

아란 같은 경우는 패시브 스킬들이 액티브 스킬에 영향을 주는 경우가 굉장히 많아서 골치아프네요. 아래는 작성하면서 생긴 의문점들입니다.

* 이 스킬은 액티브(즉발) 스킬임에도 불구하고 레전드리 어빌리티의 '패시브 스킬 레벨 1 증가' 효과의 영향을 받아 마스터 레벨이 31로 적용된다. 다만 쓸만한 컴뱃 오더스를 사용하면 마스터 레벨이 31로 오르며 32로는 오르지 않기때문에 쓸컴뱃을 사용한다면 아무런 효과가 없다. (출처: [나무위키](https://namu.wiki/w/%EC%95%84%EB%9E%80(%EB%A9%94%EC%9D%B4%ED%94%8C%EC%8A%A4%ED%86%A0%EB%A6%AC)/%EC%8A%A4%ED%82%AC#s-6.1))
* 저지먼트
  * 도트딜 미적용돼있음. 도트딜에도 스위프트 무브가 적용되는가?
  * 아드레날린일때는 저지먼트가 비활성화되는가?
* 비욘더, 스매쉬 스윙 등의 각종 파동 및 잔상류 스킬에는 패시브가 미적용인지?
* 스킬 코드를 보니 패시브 스킬 코드가 어질러져 있어 나중에 정리 필요

배틀메이지는 깔끔하게 끝났네요.

2020-08-28 12:27 UTC, icepeng commented
비숍은 지금 제가 진행중이라 넘어가시면 됩니다.

2020-08-28 12:30 UTC, icepeng requested changes

2020-08-28 12:30 UTC, icepeng commented on dpmModule/jobs/battlemage.py
> +        SpellBoost = core.InformedCharacterModifier("스펠 부스트", patt = 25 + passive_level // 2, pdamage = 10 + passive_level // 3, armor_ignore = 30 + passive_level)
마력은 버림이고 뎀퍼는 올림인데 이 부분 유의하면서 진행 부탁드립니다.

위컴알 켜고 직업 4차스킬 쭉 돌면서 common에 있는 값 참고하는게 제일 쉽습니다.

2020-08-28 12:32 UTC, cheese98 commented
보우마스터 업데이트했습니다.
* 샤프아이즈에 컴뱃 계수가 1로 적용되어 있는데 0.5에 소수점 올림으로 바꿔야 합니다. 원래 bool으로 쓰이느라 최댓값이 1이라 이렇게 작성된 것 같습니다. 다른 분들도 궁수 직업 수정할때 참고해주시기 바랍니다.
* 폭풍의 시, 가이디드 애로우의 Wrapper에서 컴뱃 계수를 요구하는 이유가 궁금합니다.
* 6레벨당 수치 증가 같은 가능성이 없는 수치도 일단 올리는 쪽으로 갈까요?

2020-08-28 12:38 UTC, icepeng commented
@cheese98 폭풍의 시, 가이디드 애로우는 제거해도 됩니다. 처음에 쓰다가 ArmorPiercingWrapper 구현이 바뀌면서 필요없어졌습니다.

가능성 없는 수치는 안하는게 가독성이 나을거 같습니다.

2020-08-28 12:39 UTC, icepeng commented
그리고 저도 처음에 까먹었는데 import math하고 math.ceil 쓰기보단 from math import ceil하고 ceil만 쓰는게 코드가 보기 편했습니다.

2020-08-28 12:47 UTC, cheese98 commented on dpmModule/jobs/battlemage.py
> +        SpellBoost = core.InformedCharacterModifier("스펠 부스트", patt = 25 + passive_level // 2, pdamage = 10 + passive_level // 3, armor_ignore = 30 + passive_level)
수정 완료했습니다. 숙련도 쪽도 잘못돼있어서 고쳤습니다.

마력퍼는 버림인거 알고 저렇게 한거긴 한데 `int()`나 함수로 바꾸는게 나을까요?

2020-08-28 18:28 UTC, icepeng commented on dpmModule/jobs/battlemage.py
> +        SpellBoost = core.InformedCharacterModifier("스펠 부스트", patt = 25 + passive_level // 2, pdamage = 10 + passive_level // 3, armor_ignore = 30 + passive_level)
버림은 그냥 // 쓰면 될거같습니다.

2020-08-29 08:36 UTC, cheese98 commented
카데나랑 캐논슈터 완료했는데 캐논슈터의 더블 럭키 다이스는 어떻게 적용해야 될지 감이 전혀 안오네요.

일단 다른 해적들도 더블 럭키 다이스는 제외하고 작업하겠습니다.

2020-08-29 08:47 UTC, icepeng commented
럭키다이스는 계산해뒀습니다. 7번 없으면 더블럭키+로디드 기댓값은 20+10/6+0.5*10/6 입니다.

2020-08-29 09:55 UTC, icepeng commented
가능성이 있는 수치는 패시브 - 마스터레벨+3, 액티브 - 마스터레벨+2 까지입니다.

가끔가다 식이 마스터레벨에서 딱 나눠떨어지지 않는 경우도 있습니다.

마스터레벨이 20인데 식이 u(x/3) 이라던가... 이런 경우에는 단순히 원래 값 뒤에 더하면 안됩니다.

2020-08-29 10:38 UTC, cheese98 commented
왠만하면 3까지는 반영하면서 하고 있습니다. 혹시나 빠뜨린 데 있으면 지적 부탁드립니다.

2020-08-29 11:00 UTC, icepeng commented
더블 럭키 다이스 레벨당 쿨타임도 4초씩 줄긴 하는데... 크게 중요한 부분은 아닙니다.

2020-08-29 11:28 UTC, icepeng commented
쿨타임 초기화를 안받는 스킬도 쿨감은 받나요?

2020-08-29 11:35 UTC, icepeng commented
그리고 이건 확인이 좀 필요한데... 원래 럭키 다이스가 있는 직업의 로디드는 벞지를 받습니다. 1~4차에 없는데 로디드로 쓰는 경우에는 모르겠어서 확인을 해야합니다.

로디드 딜레이도 지금 누락된거 같은데 정확한 딜레이를 모르겠네요.

2020-08-29 11:39 UTC, cheese98 commented
그러면 일단 로디드 직업은 미뤄두고 나머지부터 해서 올리겠습니다.

다크나이트의 경우 쿨감% 때문에 리인카 300초 쿨감을 따로 적용하는 걸로 바꿨습니다.

2020-08-29 11:42 UTC, icepeng commented
리인카가 쿨감%를 받는지 확인해봤는데 받는게 맞아보입니다. 수정하는게 맞네요.

2020-08-29 11:47 UTC, icepeng commented
더블 럭키 다이스 + 로디드는 첫 2개가 같으면 3번째도 같은게 나올 확률이 50% 감소하네요... 계산에 포함을 안했습니다. 정리가 다 되면 같이 수정해야겠네요.

2020-08-29 11:49 UTC, cheese98 commented
그럼 앞에서 나온 이슈랑 관련 없는 직업들부터 계속 진행하도록 하겠습니다.

2020-08-30 11:50 UTC, cheese98 commented
듀얼블레이드도 컴뱃 적용을 완료했습니다.

https://github.com/oleneyl/maplestory_dpm_calc/blob/6fa127c4404982542efd7c846d539b20ab27029a/dpmModule/jobs/dualblade.py#L78

그런데 페이탈 베놈이 160% 3타인데 `core.DotSkill`의 한계 때문에 타수를 곱하는 걸로 구현되어 있네요. 점유율도 낮고 다른 거 건드리면 너무 복잡해지기 때문에 일단 놔뒀지만 나중에 도트 스킬에도 타수를 적용할 수 있게 바꿨으면 좋겠습니다.

2020-08-30 11:52 UTC, icepeng commented
도트스킬에 타수 적용되게 바꾸는건 간단합니다. 당연히 1타만 되는줄 알고 해둔건데 바꿔야겠네요...

2020-08-30 12:38 UTC, cheese98 commented
에반
----
서클 오브 마나 데미지값 재확인 필요
* 30레벨 기준 290*4 + 330*4이면 315*8이 아니라 310*8이 돼야 합니다.
* 가능하면 평균치를 쓰지 않고 직접 구현하는 것이 더 좋을듯합니다.
* 데미지값 차이와 컴뱃 계수는 연관이 없으므로 컴뱃 적용은 완료됐습니다.

드래곤 브레스 쿨타임, 기존스킬 뎀퍼
* 쿨타임: 툴팁상에는 10초, 코드상에는 7.5초
* 서클오브윈드 (1): 퍼뎀, 타수 이상함
* 드래곤 스위프트 (2): 없음
* 서클 오브 썬더 (1): 적용은 했으나 퍼뎀 이상함
* 다이브 오브 썬더 (1): 없음

다크 포그: 미구현 (미사용인가요?)

나머지는 다 적용 완료됐습니다.

2020-08-30 12:42 UTC, icepeng commented
마크다운에서 \*으로 문자열 양쪽을 감싸면 *이렇게* 되기 때문에 `\*` 를 사용해서 적어야 합니다.

다크 포그는 아마 조디악 발동 사이클에 들어갈겁니다. 퍼뎀 타수 등등 에반 수정할때 고쳐두겠습니다.

2020-08-30 12:53 UTC, cheese98 commented
확인해주셔서 감사합니다.

혹시 팔라딘도 코드 갈아엎어야 하나요?

2020-08-30 13:03 UTC, icepeng commented
팔라딘은 끝났습니다.

2020-08-30 13:05 UTC, cheese98 commented
팔라딘 보니까 컴뱃은 적용돼있는데 패시브 스킬레벨 관련 코드는 아직 없네요. 순서 오면 추가해 놓을까요?

2020-08-30 13:13 UTC, icepeng commented
패시브 레벨에 영향받는게 엑스퍼트, 어드밴스드 차지 2개 있겠네요. 추가해두면 되겠습니다.

2020-08-31 12:21 UTC, cheese98 commented
카이저
---
인퍼널 브레스
* 쿨타임이 미적용돼있음
  * 적용시 쿨타임: `(20-self._combat)/*1000`
* 도트 데미지 미구현

키네시스
---
* 얼티메이트-B.P.M: 트레인 패시브 미적용
* 무빙 매터(최종), 싸이킥 불릿(블랙홀)에 각성의 크뎀효과가 미적용

2020-08-31 12:41 UTC, cheese98 commented
내일부터 5개씩 하면 목요일쯤 마지막까지 갈 것 같고, 그 이후로는 앞에서 누락된 직업들 마저 작업하면 될 것 같습니다.

2020-08-31 12:57 UTC, icepeng commented on dpmModule/jobs/hero.py
>      def __init__(self, skill, desfortBuff, vEhc, combat = False):
combat의 default parameter는 제거하는게 낫겠네요.

2020-08-31 13:06 UTC, cheese98 commented on dpmModule/jobs/hero.py
>      def __init__(self, skill, desfortBuff, vEhc, combat = False):
수정 완료했습니다.

2020-08-31 13:21 UTC, icepeng commented
얼티메이트 크뎀 패시브는 5차 스킬에도 적용되는게 맞습니다.

얼티메이트-B.P.M: 트레인 뎀증 패시브에 컴뱃 미적용 < 패시브에 메테리얼도 같이 있지 않나요? 트레인에도 적용하면 되지 않을까요?

2020-08-31 13:56 UTC, icepeng commented
그리고 이쯤에서 머지하고, 나머지는 직업마다 pr을 따로 만드는게 좋겠습니다. pr 하나가 오래 길어지면 master에 다른 직업 수정이 들어왔을때 컨플릭트가 날 확률이 높아져서요.

2020-08-31 14:27 UTC, cheese98 commented
고생 많으셨습니다. 일단 merge해주시면 나머지 작업분은 다 모아서 한번에 올리겠습니다.

2020-08-31 14:32 UTC, icepeng commented
여기서 발견한 이상한 점들은 직업별로 이슈 작성해주시면 나중에 작업에 참고하겠습니다.

2020-08-31 14:33 UTC, cheese98 commented
알겠습니다. 빠른 시일 내에 직업별로 이슈 정리해서 올리겠습니다.

2020-08-31 14:34 UTC, merged

2020-08-31 18:02 UTC, icepeng commented on dpmModule/jobs/aran.py
> +        AdrenalineFinalBlow = core.DamageSkill("파이널 블로우(아드레날린)", 420, 420, 285 + 100 + (60 + 2 * passive_level) + (20 + passive_level) + 150, 7, modifier=core.CharacterModifier(armor_ignore=15)).setV
어쩌다가 나온 실수인지 모르겠는데... 420이 두번 들어가면서 무려 615타짜리 스킬이 되어버렸네요.

test.py 돌릴떄 --stat 옵션 주고 돌리면 스킬별 정보와 점유율이 나오니 커밋 전에 확인하는게 좋겠습니다.

2020-08-31 18:15 UTC, icepeng commented on dpmModule/jobs/evan.py
> +        MagicParticle = core.DamageSkill("마법 잔해", 0, 110+2*self._combat + 4*(100+self._combat), 15, cooltime = 10000).setV(vEhc, 5, 2, True).wrap(core.DamageSkillWrapper)
마법 잔해 최대 생성제한 15개, 5개당 100%p 증가이므로 `110+2*self._combat + 3*(100+self._combat`) 입니다.

2020-08-31 18:16 UTC, icepeng commented on dpmModule/jobs/evan.py
> +        MagicParticle = core.DamageSkill("마법 잔해", 0, 110+2*self._combat + 4*(100+self._combat), 15, cooltime = 10000).setV(vEhc, 5, 2, True).wrap(core.DamageSkillWrapper)
그리고 강화된 마법 잔해는 패시브라 _combat이 아닌 passive_level을 사용해야 합니다.

2020-08-31 18:31 UTC, icepeng commented on dpmModule/jobs/kaiser.py
> +        return [InnerBlaze, AdvancedInnerBlaze, IronWill, Catalyze,
아이언 윌은 모프 게이지 단계당 데미지 3%씩 증가라 안넣어 둔거 같은데... 이런 변경도 있으면 커밋 메세지 하단에 같이 써두는게 좋습니다.

```
카이저 컴뱃 오더스 적용

* 패시브 스킬에 리턴 배열에 누락된 IronWill 추가
```

이렇게요.

2020-08-31 18:40 UTC, icepeng commented on dpmModule/jobs/kinesis.py
> +                             ESPBattleOrder, Transcendence, SupremeConcentration, Transport, Mastery]
이것도 카이저와 마찬가지입니다.

2020-08-31 22:47 UTC, cheese98 commented on dpmModule/jobs/aran.py
> +        AdrenalineFinalBlow = core.DamageSkill("파이널 블로우(아드레날린)", 420, 420, 285 + 100 + (60 + 2 * passive_level) + (20 + passive_level) + 150, 7, modifier=core.CharacterModifier(armor_ignore=15)).setV
윽.. 죄송합니다 다른건 다 테스트 돌려보고 올리는데 아란은 깜빡했었네요

2020-09-01 16:49 UTC, icepeng commented on dpmModule/jobs/cadena.py
> +        CheapShotIIBleed = core.SummonSkill("위크포인트 컨버징 어택 출혈", 0, 1000, 70 + 2 * passive_level, 0.01 * (30 + passive_level), 99999999).wrap(core.SummonSkillWrapper)
출혈 퍼뎀 타수가 뭔가 이상한데요... `70 + 2 * (20 + passive_level)`, `0.01 * (30 + 20 + passive_level)` 아니였을까요? 그리고 확률은 어차피 여러번 치면 100% 가동률이 나와서 1타로 취급해도 상관이 없을거예요. 그리고 출혈은 DotSkill로 취급해야 할겁니다. 디버프로 들어가는 도트딜은 뎀퍼 보공 최종뎀 크확이 안들어가서 DotSkill을 만들었습니다.

일단... 제가 어차피 카데나 작업해야 하니 같이 수정해두겠습니다.