컴뱃 오더스 적용 (2)
oleneyl/maplestory_dpm_calc pull request #323
Opened 2020-09-01 02:54 UTC by cheese98

제로까지 끝마쳤습니다. 

미하일
* 영메 렙차 적용여부

나이트로드
* 써든레이드 미구현
* 베놈 타수 분리 필요

팔라딘
* 어드밴스드 차지 미구현 (컴뱃 영향은 안받음)
* 생츄어리 미적용

패스파인더
* 기능상 이상은 없으나 여러 패시브 스킬들이 혼합되어 있어 정리 필요

섀도어
* 써든레이드 미사용

바이퍼
* 파이널어택 미적용
* 럭키 다이스 미적용

와일드헌터
* `super(core.DamageSkillWrapper, self).__init__(skill, 3)` 오류로 인한 테스트 불가
* 드릴 컨테이너, 재규어 맥시멈 미구현
* 윌 오브 리버티 미사용

제로
* 어드밴스드 스톰 브레이크, 어드밴스드 어스 브레이크 전기지역 스킬 도트화해야함

2020-09-01 02:57 UTC, cheese98 commented
썬콜, 불독, 아크, 캡틴, 데벤을 제외하면 다 완료된 상태입니다.

2020-09-01 05:57 UTC, icepeng commented
섀도어는 써든레이드 쓸 시간에 암살 한번 더치는게 더 셉니다. 킬링 포인트를 받는 한은.

팔라딘의 어드밴스드 차지는 패시브의 엘리멘탈 차지에 합산되어 있고, 타수도 디차/라차에 적용되어 있습니다.

2020-09-01 05:58 UTC, icepeng commented on dpmModule/jobs/paladin.py
> +        self._combat = 2
팔라딘은 해당 변수 굳이 안넣어도 됩니다.

2020-09-01 06:03 UTC, icepeng commented on dpmModule/jobs/paladin.py
> +        PaladinExpert = core.InformedCharacterModifier("팔라딘 엑스퍼트(두손둔기)",crit_damage = 15+passive_level//3+5, pdamage_indep = 42+passive_level, crit = 42+passive_level, armor_ignore = 37.9)
이미 32레벨을 가정하고 입력해둔 수치였는데, 패시브 레벨+1로 인해 33렙이 되면 16+5가 되는게 맞습니다.

지금 코드로는 패시브+1이 들어가도 15+5가 됩니다.

`15 + (2 + passive_level) // 3 + 5` 로 바꾸거나, passive_level 자체를 `chtr.get_base_modifier().passive_level + 2`로 정의해두고 최종뎀, 크확을 `40+passive_level`로 바꾸거나... 하는게 좋겠네요.

2020-09-01 06:08 UTC, cheese98 commented on dpmModule/jobs/paladin.py
> +        PaladinExpert = core.InformedCharacterModifier("팔라딘 엑스퍼트(두손둔기)",crit_damage = 15+passive_level//3+5, pdamage_indep = 42+passive_level, crit = 42+passive_level, armor_ignore = 37.9)
안그래도 이거 두손검 기준으로 수정해야 됩니다. 아예 새로 짜도록 하겠습니다.

2020-09-01 06:12 UTC, icepeng commented on dpmModule/jobs/paladin.py
> +        PaladinExpert = core.InformedCharacterModifier("팔라딘 엑스퍼트(두손둔기)",crit_damage = 15+passive_level//3+5, pdamage_indep = 42+passive_level, crit = 42+passive_level, armor_ignore = 37.9)
왜 두손검 기준으로 수정해야 하나요?

2020-09-01 06:15 UTC, cheese98 commented on dpmModule/jobs/paladin.py
> +        self._combat = 2
https://github.com/oleneyl/maplestory_dpm_calc/blob/a179da58da50e6809aa26b54ba6d81092a284bbc/dpmModule/jobs/__init__.py#L136

코드 상에서는 이미 두손검을 이용하고 있습니다.

2020-09-01 06:15 UTC, cheese98 commented on dpmModule/jobs/paladin.py
> +        PaladinExpert = core.InformedCharacterModifier("팔라딘 엑스퍼트(두손둔기)",crit_damage = 15+passive_level//3+5, pdamage_indep = 42+passive_level, crit = 42+passive_level, armor_ignore = 37.9)
https://github.com/oleneyl/maplestory_dpm_calc/blob/a179da58da50e6809aa26b54ba6d81092a284bbc/dpmModule/jobs/__init__.py#L136

코드 상에서는 이미 두손검을 이용하고 있습니다.

2020-09-01 06:18 UTC, cheese98 commented
생츄어리는 제가 잘못 본 것 같습니다. 어드밴스드 차지 적용된 건 방금 확인했습니다. 문제 없네요.

2020-09-01 06:20 UTC, icepeng commented on dpmModule/jobs/paladin.py
> +        PaladinExpert = core.InformedCharacterModifier("팔라딘 엑스퍼트(두손둔기)",crit_damage = 15+passive_level//3+5, pdamage_indep = 42+passive_level, crit = 42+passive_level, armor_ignore = 37.9)
그건...바꿔야겠네요. 두손검을 두손둔기로 바꾸건 패시브를 바꾸건... 제일 좋은건 다 만들어두고 장착중인 무기를 참조하는 것인데 지금 구조상 불가능하네요.

2020-09-01 06:21 UTC, cheese98 commented on dpmModule/jobs/paladin.py
> +        PaladinExpert = core.InformedCharacterModifier("팔라딘 엑스퍼트(두손둔기)",crit_damage = 15+passive_level//3+5, pdamage_indep = 42+passive_level, crit = 42+passive_level, armor_ignore = 37.9)
그러면 지금 두손검 장착으로 계산이 되고 있으니 일단 그쪽에 맞춰서 스킬 코드를 수정해놓을까요?

2020-09-01 06:36 UTC, cheese98 commented
* `self._combat` 제거
* 팔라딘 엑스퍼트 전체레벨 기준으로 계산하도록 변경
* 무기별 보너스 옵션 분리
수정 전 값과 동일한 것을 확인했습니다.

2020-09-01 06:42 UTC, icepeng commented on dpmModule/jobs/paladin.py
> +        PaladinExpert = core.InformedCharacterModifier("팔라딘 엑스퍼트(두손둔기)",crit_damage = 15+passive_level//3+5, pdamage_indep = 42+passive_level, crit = 42+passive_level, armor_ignore = 37.9)
두손검이나 두손둔기나 무기 종류만 다르지 무기상수, 무기공이 똑같아서 큰 의미는 없습니다.

직업별로 표기해둔 무기명도 사실상 WeaponFactory에서 기본공, 공추옵 가져오는 용도밖에 안되긴 합니다.

2020-09-01 13:46 UTC, icepeng requested changes
수정하다 발견한 이상한 점은 이슈로 따로 작성해두고, pr 자체 내용에는 어떤 직업에 어떤 변경들이 가해졌는지만 요약하는게 나중에 변경내역 작성하기가 쉬울거 같습니다.

2020-09-01 13:46 UTC, icepeng commented on dpmModule/jobs/wildhunter.py
> +        WildBalkan = core.DamageSkill("와일드 발칸", 120, 370 + 2*self._combat, 1, modifier = core.CharacterModifier(boss_pdamage=10+20, pdamage=20)).setV(vEhc, 0, 2, False).wrap(core.DamageSkillWrapper)
저번 pr에도 언급했듯이 이런 수정도 커밋 메세지에 포함해주시면 확인하기 편해집니다.

2020-09-01 13:46 UTC, icepeng commented on dpmModule/jobs/striker.py
> +        NuckleExpert = core.InformedCharacterModifier("너클 엑스퍼트",att = 30 + passive_level, crit_damage = 30 + passive_level)
크뎀 20이 맞습니다.

2020-09-01 13:46 UTC, icepeng commented on dpmModule/jobs/phantom.py
> +        FinalCut = core.DamageSkill("탤런트 오브 팬텀시프 IV(파이널 컷)", 450, 2000 + 20 * self._combat, 1, modifier = core.CharacterModifier(pdamage_indep = 100*((STEALSKILL_CONSTANT / 1.3)-1)),cooltime = 90000,
`core.CharacterModifier(pdamage_indep = 100*((1.2/1.3)-1))` 전체를 STEALSKILL_MODIFIER로 빼는건 어떨까 싶네요.

스틸스킬로 사용한 스킬은 무기상수가 1.2로 적용된다는 설명도 함께 해두는게 좋을거 같습니다. 설명 없이는 알기가 힘든 부분이네요.

2020-09-01 16:15 UTC, icepeng commented
> super(core.DamageSkillWrapper, self).__init__(skill, 3) 오류로 인한 테스트 불가

이건 재현이 안되어서 모르겠습니다. 사실 이 구현 자체가 꼼수라서 바꾸긴 해야하는데, 동작은 되고있긴 합니다.

2020-09-02 01:00 UTC, cheese98 commented on dpmModule/jobs/striker.py
> +        NuckleExpert = core.InformedCharacterModifier("너클 엑스퍼트",att = 30 + passive_level, crit_damage = 30 + passive_level)
제가 아크의 너클 엑스퍼트를 보고 잘못 입력했었네요...

2020-09-02 01:03 UTC, cheese98 commented on dpmModule/jobs/phantom.py
> +        FinalCut = core.DamageSkill("탤런트 오브 팬텀시프 IV(파이널 컷)", 450, 2000 + 20 * self._combat, 1, modifier = core.CharacterModifier(pdamage_indep = 100*((STEALSKILL_CONSTANT / 1.3)-1)),cooltime = 90000,
사실 적용 스킬이 파컷밖에 없어서 직접 넣은 거긴 한데, 나중에 메타가 바뀔 것을 대비해서 분리해 놓겠습니다.

2020-09-02 01:42 UTC, cheese98 commented
* 너클 엑스퍼트 오류수정: 제가 실수로 아크에 있는 동일한 이름의 스킬을 스커에 적용시켰습니다.
* 팬텀 스틸스킬 무기상수 분리
* 캡틴 컴뱃오더스 적용 (#330 참고)

2020-09-02 12:39 UTC, icepeng approved these changes

2020-09-02 18:57 UTC, merged

2020-09-09 05:43 UTC, icepeng commented on dpmModule/jobs/pathfinder.py
> +        CardinalDischarge = core.DamageSkill("카디널 디스차지", 360+5*passive_level, (4 + 1)*2, 300, modifier = core.CharacterModifier(pdamage = 20)).setV(vEhc, 0, 2, True).wrap(core.DamageSkillWrapper)
퍼뎀이 아닌 딜레이에 컴뱃이 들어갔네요. 수정해두겠습니다.