매직 서킷 풀드라이브 패치
oleneyl/maplestory_dpm_calc pull request #415
Opened 2020-09-16 13:15 UTC by cheese98

아크
---
```
Before
매직 서킷 풀드라이브(마력 폭풍) Used 46 Delay 0
After
매직 서킷 풀드라이브(마력 폭풍) Used 113 Delay 0
```

아직 아델 139회, 일리움 135회보다는 꽤 밀리지만 수정을 거치면 비슷해질 것 같습니다.

2020-09-27 13:19 UTC, cheese98 commented
일리움
-----
```
Before
매직 서킷 풀드라이브(마력 폭풍) Summoned 9 Delay 0
Used 135 Hit 405
Damage 221162319121.9 Loss -0.0

After
매직 서킷 풀드라이브(마력 폭풍) Used 130 Delay 0
Hit 390 Damage 206909281114.5 Loss -0.0
```

2020-09-27 14:19 UTC, oleneyl commented on dpmModule/jobs/ark.py
> +        #MagicCircuitFullDriveStorm = core.DamageSkill("매직 서킷 풀드라이브(마력 폭풍)", 0, 500+20*vEhc.getV(4,3), 3, cooltime=4000).wrap(core.DamageSkillWrapper)
굳이 주석처리가 된 이유가 있을까요?

2020-09-27 14:20 UTC, oleneyl commented
매서풀에 대해 어떤 변경점인가요?

2020-09-27 14:25 UTC, cheese98 commented
지금 일리움 매서풀은 소환수로 취급되어서 일정 시간마다 반드시 타격하는데 인게임 스킬 로직하고 미세하게 어긋납니다.

그래서 아크, 아델처럼 공격 스킬에 반응하도록 변경했습니다.

2020-09-27 15:29 UTC, icepeng requested changes

2020-09-27 15:29 UTC, icepeng commented on dpmModule/jobs/ark.py
> +        #MagicCircuitFullDrive = core.BuffSkill("매직 서킷 풀드라이브", 720, (30+vEhc.getV(4,3))*1000, pdamage = (20 + vEhc.getV(4,3)), cooltime = 200*1000, red=True).isV(vEhc,4,3).wrap(core.BuffSkillWrapper)
주석

2020-09-27 15:29 UTC, icepeng commented on dpmModule/jobs/ark.py
> +        #MagicCircuitFullDrive = core.BuffSkill("매직 서킷 풀드라이브", 720, (30+vEhc.getV(4,3))*1000, pdamage = (20 + vEhc.getV(4,3)), cooltime = 200*1000, red=True).isV(vEhc,4,3).wrap(core.BuffSkillWrapper)
어차피 history가 남기 때문에 정말 특별한 이유 없으면 그냥 지우는게 좋습니다.

2020-09-27 15:29 UTC, icepeng commented on dpmModule/jobs/ilium.py
> +        for sk in [Craft_Orb, Reaction_Domination, Craft_Javelin, Craft_Javelin_AfterOrb, Reaction_Destruction, Craft_Longinus, CrystalSkill_MortalSwing, GloryWing_MortalWingbit, GloryWing_Craft_Jave
리액션 스킬에 매서풀이 발동하는지 모르겠네요. 사실 발동하거나 말거나 자벨린/오브 직후에 리액션 스킬이 터지기 때문에 빼도 상관없지 싶습니다. 그리고 크리스탈 이그니션 키다운중에도 매서풀이 터져야 할거 같습니다.

2020-09-27 15:29 UTC, icepeng commented on dpmModule/jobs/ilium.py
> +        #MagicCircuitFullDrive.onAfter(MagicCircuitFullDriveStorm)
마찬가지로 주석

2020-09-27 15:29 UTC, icepeng commented on dpmModule/jobs/ilium.py
> +        for sk in [Craft_Orb, Reaction_Domination, Craft_Javelin, Craft_Javelin_AfterOrb, Reaction_Destruction, Craft_Longinus, CrystalSkill_MortalSwing, GloryWing_MortalWingbit, GloryWing_Craft_Jave
그나저나 코드 위치도 이상하네요. 스킬 연결하는 쪽으로 내려야 합니다.

2020-09-27 23:48 UTC, cheese98 commented
변경 완료했습니다. 지금 아델 매서풀이 디바이드랑 레조넌스에만 발동되게 돼있는데 이게 맞는지 확인해봐야겠네요.

2020-10-09 13:14 UTC, cheese98 commented
매서풀
o
디바이드, 레조넌스, 샤드, 오더, 마커, 리스토어, 루인, 스톰
x
테리토리, 스콜, 그레이브
?
크리에이션, 게더링, 블로섬

2020-11-18 08:27 UTC, cheese98 commented
#506 과의 confilct 발생으로 인해 닫고 #520, #521 로 대체하겠습니다.

2020-11-18 08:27 UTC, closed without merging