스커 파섬 추가
oleneyl/maplestory_dpm_calc pull request #488
Opened 2020-09-22 23:45 UTC by cheese98

기존 코드는 유지했습니다.

2020-09-23 17:25 UTC, oleneyl commented
벽섬을 안쓰게 되나요?

2020-09-23 23:15 UTC, cheese98 commented
네, 수정본에서는 벽력이 파도로 대체됩니다.

2020-09-24 06:25 UTC, icepeng commented
related #486

2020-09-26 04:29 UTC, oleneyl commented
dpm이 더 높게 나오는거죠? @icepeng 추가이슈 있으신가요?

2020-09-26 04:30 UTC, oleneyl approved these changes

2020-09-26 04:32 UTC, icepeng requested changes

2020-09-26 04:32 UTC, icepeng commented on dpmModule/jobs/striker.py
> +        천지개벽 OFF: 벽력 - 섬멸 or 파도 - 섬멸
그냥 파섬으로 바꿔쓰는게 맞지 않을까요?

2020-09-26 04:32 UTC, icepeng commented on dpmModule/jobs/striker.py
> +        #BasicAttack = core.OptionalElement(SkyOpen.is_active, HurricaneDestroy, ThunderDestroy)
별로 주석 남겨둘 필요가 없어보입니다.

2020-09-26 04:32 UTC, icepeng commented on dpmModule/jobs/striker.py
>          코강 : 10개
코강 관련 docstring 그냥 지우는게 좋을거 같습니다. 어차피 풀코강이기 때문에.

2020-09-26 05:13 UTC, cheese98 commented on dpmModule/jobs/striker.py
>          코강 : 10개
3개 모두 수정 완료했습니다.

2020-09-26 07:04 UTC, merged