kmst 1.2.109 적용
oleneyl/maplestory_dpm_calc pull request #510
Opened 2020-10-15 05:58 UTC by cheese98

2020-10-15 06:32 UTC, cheese98 commented
윈드 오브 프레이에 파이널 어택 터지는지 확인필요

2020-10-16 06:56 UTC, icepeng commented on dpmModule/jobs/bowmaster.py
> +                    QuibberFullBurstDOT, GrittyGust, ImageArrowPassive,
이거 DOT만 넣어둔거 의도된겁니다.

2020-10-16 06:58 UTC, cheese98 commented on dpmModule/jobs/bowmaster.py
> +                    QuibberFullBurstDOT, GrittyGust, ImageArrowPassive,
그러면 본섭 패치 들어올때 롤백해놓겠습니다.

2020-10-16 07:34 UTC, icepeng commented on dpmModule/jobs/bowmaster.py
> +                    QuibberFullBurstDOT, GrittyGust, ImageArrowPassive,
윈드 오브 프레이 안쓰는게 아마 dpm이 더 높을텐데

1. GrittyGust, GrittyGustDOT 둘다 빼거나
2. 둘다 넣고 Ruleset에 DisableRule("윈드 오브 프레이") 추가하거나

둘중 하나로 하면 되겠습니다

2020-10-22 04:04 UTC, cheese98 commented
* 본섭 써든레이드 타수변경 적용
* 나로 스프 꺼져있을때 쿨마다 써레 사용

2020-10-22 08:50 UTC, icepeng requested changes

2020-10-22 08:50 UTC, icepeng commented on dpmModule/jobs/nightlord.py
> +        def is_suddenraid():
BasicAttack을 굳이 만들지 않고 원래대로 QuadrapleThrow 사용하고, SuddenRaid 사용가능 여부는 Rule쪽에서 처리하는게 맞겠네요.

2020-10-22 09:40 UTC, cheese98 commented on dpmModule/jobs/nightlord.py
> +        def is_suddenraid():
수정 완료하고 값 동일하게 나오는 것도 확인했습니다. 훨씬 깔끔하네요.

2020-10-22 12:47 UTC, oleneyl approved these changes

2020-10-22 12:48 UTC, icepeng approved these changes

2020-10-22 12:53 UTC, merged