fix: 제로 오라스위칭 구현
oleneyl/maplestory_dpm_calc pull request #527
Opened 2020-11-21 09:23 UTC by cheese98

#525 

리미트 브레이크와 타임 디스토션에는 공격속도 증가 효과가 있기 때문에 지속 시간동안 오라를 디바인 포스로 교체하여 공격력 20을 얻을 수 있음.

```
데이터 (유니온 6000 기준)

변경 전 (리밋브에만 활성화): 749586503639.9348
변경 후 (리밋브 or 디토에 활성화): 752063492633.2917
대조군 (디바인포스 가동률 100% + 찐윈부): 756827798817.2253
```

DevineAuraWrapper를 BuffSkillWrapper를 상속하여 선언시 get_modifier가 작동하지 않아 StackSkillWrapper로 임시조치했습니다. CriticalBindWrapper는 잘만 되는데 제가 짠 코드는 왜 안되는지 모르겠습니다... 원인을 아는 분께서 해결해주시면 감사하겠습니다.

2020-11-25 05:19 UTC, cheese98 commented
추가로 쉐도우 스트라이크의 딜 상승 여부에 대해 조사 중입니다.

2020-11-28 03:57 UTC, cheese98 commented
`BuffSkillWrapper` 상속 클래스에서 `get_modifier` 미작동하는 원인 확인될때까지 보류

2020-12-08 15:54 UTC, icepeng requested changes

2020-12-08 15:54 UTC, icepeng commented on dpmModule/jobs/zero.py
>  # BuffSkillWrapper로 선언시 get_modifier가 작동하지 않아 StackSkillWrapper로 임시조치
만료된 주석 제거해주세요

2020-12-08 15:55 UTC, cheese98 commented
`.\dpmModule\jobs\zero.py:357:70: E231 missing whitespace after ','`

#611 과의 충돌을 피하기 위해 일부러 수정하지 않았습니다.

2020-12-08 16:10 UTC, cheese98 commented
| | Before | After | Diff |
| - | - | - | - |
| 6000 | 777256987990.1506 | 780015175538.807 | 0.35% |
| 8000 | 4491686027827.376 | 4499967702126.453 | 0.18% |

2020-12-09 11:25 UTC, icepeng commented on dpmModule/jobs/zero.py
> +        LuckyHat_Temp_6000 = core.InformedCharacterModifier("카오스 벨룸의 헬름 (임시)", boss_pdamage=30) - core.ExtendedCharacterModifier(armor_ignore=10, stat_main=21, stat_sub=21, pstat_main=5, pstat_sub=5,
Extended끼리 뺄셈하는게 안전할거 같네요

2020-12-09 11:27 UTC, cheese98 commented on dpmModule/jobs/zero.py
> +        LuckyHat_Temp_6000 = core.InformedCharacterModifier("카오스 벨룸의 헬름 (임시)", boss_pdamage=30) - core.ExtendedCharacterModifier(armor_ignore=10, stat_main=21, stat_sub=21, pstat_main=5, pstat_sub=5,
변경 완료했습니다

2020-12-09 11:31 UTC, icepeng approved these changes

2020-12-09 11:32 UTC, merged