바이퍼 타임리프 (#568)
oleneyl/maplestory_dpm_calc pull request #570
Opened 2020-12-03 11:10 UTC by cheese98

제가 측정한 결과로는 사용하지 않는 것이 더 높게 나오므로 구현만 해둔 상태로 올립니다.

2020-12-03 11:23 UTC, cheese98 commented
도저히 딜을 올릴 방법을 찾을수가 없어 시트에 "타임 리프 미사용" 문구를 추가합니다.

2020-12-03 13:40 UTC, icepeng requested changes

2020-12-03 13:40 UTC, icepeng commented on dpm_sheet.py
> +        ("바이퍼", "카운터 어택 미발동, 타임 리프 미사용", {}, 0),
굳이 언급할 필요 없는거 같습니다. 버프 사용같은건 최적으로 돌아간다고 치고, 여긴 측정 환경별로 달라질 수 있는 조건 혹은 기본 딜사이클을 명시하는 것입니다.

2020-12-03 13:42 UTC, cheese98 commented on dpm_sheet.py
> +        ("바이퍼", "카운터 어택 미발동, 타임 리프 미사용", {}, 0),
수정 후 force push 하도록 하겠습니다.

2020-12-09 11:26 UTC, icepeng requested changes
반환 배열에 타임리프 추가는 하고, ruleset에서 DisableRule 걸어주세요.

2020-12-09 11:34 UTC, icepeng approved these changes

2020-12-09 11:34 UTC, merged