flake8 대응 코드 정리
oleneyl/maplestory_dpm_calc pull request #621
Opened 2020-12-09 06:21 UTC by cheese98

#503

제논 딜사이클 제보를 바탕으로 수정해 나갈 예정입니다.

2020-12-14 19:04 UTC, icepeng requested changes

2020-12-14 19:04 UTC, icepeng commented on dpmModule/jobs/xenon.py
>      def chargeController(self):
굳이 아마란스 제너레이터에 chargeController 쓰지 않고, stackController(40)으로 처리해도 무방해보여요

2020-12-14 19:08 UTC, icepeng commented on dpmModule/jobs/xenon.py
>          MeltDown.onAfter(MeltDown_Damage)
MeltDown_Armor도 마찬가지네요

2020-12-15 01:02 UTC, cheese98 commented on dpmModule/jobs/xenon.py
>      def chargeController(self):
굳이 method를 만들 필요가 없었네요... 리뷰 내용 전부 다 수정해놨습니다.

2020-12-20 15:53 UTC, cheese98 commented
생각해보니 제논은 스탯을 하나에 몰아주지 않고 분배해야 되기 때문에 제논 전용 메용이랑 메용2를 따로 만들어야겠네요

2020-12-23 16:05 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +               [PinpointRocket, PinpointRocketOpt, Triangulation, OOPArtsCode] +
Opt 넣을필요 없을거예요

2020-12-23 19:15 UTC, icepeng commented
쿨감받는 스킬에 rem=True 빠진게 많네요.

아마 홀로그램 그래피티는 소환수지속 받을거 같은데 확인해주세요.

2020-12-23 19:37 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +        ruleset.add_rule(ConcurrentRunRule('포톤 레이', '홀로그램 그래피티 : 융합'), RuleSet.BASE)
포톤레이 이렇게 하면 사용횟수 손해가 심할거예요. ConditionRule으로 융합이 켜져있거나 / 융합 남은 쿨타임이 일정 이상일 때 사용으로 하는게 좋겠네요. 그냥 쿨마다 쓰게 해도 되고요.

2020-12-23 19:37 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +        ruleset.add_rule(ConditionRule('엑스트라 서플라이', '서플러스 서플라이', lambda sk : sk.stack < sk._max), RuleSet.BASE)
sk._max - 10보다 작을때로 하는게 더 효율적이겠네요.

2020-12-23 19:37 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +        return ruleset
아마란스 제너레이터를 두번에 한번씩 오버로드에 맞추는게 필요해 보이네요,

2020-12-23 19:37 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +    return core.BuffSkill("메이플 용사", 0, (900+15*combat_level)*1000,
매직넘버 652, 326에 대한 설명이 너무 부족하네요.

2020-12-23 19:37 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +        MinoritySupport = core.InformedCharacterModifier("마이너리티 서포트", stat_main=20, stat_sub=20, stat_main_fixed = 50527*0.4)
50527*0.4는 뭐죠?

2020-12-23 19:56 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +        Hologram_Fusion_Buff = core.BuffSkill("홀로그램 그래피티 : 융합 (버프)", 0, 30000+10000, pdamage=5+vEhc.getV(4, 4)//2, rem=False).wrap(core.BuffSkillWrapper)
융합(버프)를 시전하는 코드가 안보이네요.

2020-12-23 20:05 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +                globalSkill.useful_wind_booster(), globalSkill.useful_hyper_body_xenon(), XenonMapleHeroes2(vEhc, 0, 0, chtr.level, self.combat), globalSkill.soul_contract(),
익스그린으로 풀공속 가능하면 쓸윈부는 안넣는게 맞아보이네요

2020-12-23 20:08 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +        PhotonRay = core.BuffSkill("포톤 레이", 300, 20000, cooltime=35000).wrap(core.BuffSkillWrapper)
포톤레이 차징 모션도 딜레이 0으로 가능하다고 하네요.

2020-12-23 20:26 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +        MegaSmasher.onAfter(core.RepeatElement(MegaSmasherTick, 64))
스매셔 풀히트시 78회 반복, 틱당 딜레이는 210ms가 맞아보이네요.

2020-12-23 20:43 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +        ruleset.add_rule(ConcurrentRunRule('레디 투 다이', '홀로그램 그래피티 : 융합'), RuleSet.BASE)
옵드도 융합에 맞추는게 전 살짝 좋게 나왔는데, 테스트해보면 좋을거 같아요.

2020-12-23 20:48 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +        MeltDown_Armor = core.BuffSkill("멜트다운 익스플로전 (방무)", 0, 10000, armor_ignore=30, rem=False).wrap(core.BuffSkillWrapper)
이거 버그가 있는데요, MeltDown_Armor, MeltDown_Damage를 cooltime=-1이 아닌, protect_from_running으로 처리하면 이게 자벞 취급이 되면서 처음에 캐싱되고 상시 적용 버프로 계산되어 버려요. 그러니 protect_from_running 목록에서 두개 제거하고, cooltime=-1을 붙여주셔야 할거 같아요.

2020-12-23 20:50 UTC, icepeng commented
여기까지 리뷰된 내용 전부 적용하면, 실제 허수아비 6분 타격 전분과 비교했을 때 점유율, 딜량 모두 정확도 높은 것 확인했습니다.

리뷰된 내용 전부 적용되면 머지해도 좋을거 같아요.

2020-12-23 21:04 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +    return core.BuffSkill("메이플 용사", 0, (900+15*combat_level)*1000,
주스탯/부스탯 어렵게 생각하지 말고, 그냥 부스탯0에 주스탯만 있는걸로 취급하고, 메용이나 메용2 둘다 주스탯을 일정량 주는걸로 해도 충분하지 않을까요?

2020-12-23 23:24 UTC, cheese98 commented on dpmModule/jobs/xenon.py
> +        MinoritySupport = core.InformedCharacterModifier("마이너리티 서포트", stat_main=20, stat_sub=20, stat_main_fixed = 50527*0.4)
이거는 개인적으로 테스트 해보던거 실수로 딸려 들어온 것 같네요...

2020-12-23 23:33 UTC, cheese98 commented on dpmModule/jobs/xenon.py
> +    return core.BuffSkill("메이플 용사", 0, (900+15*combat_level)*1000,
일단 공용 코드로 돌려놓겠습니다.

2020-12-23 23:34 UTC, cheese98 commented on dpmModule/jobs/xenon.py
> +        ruleset.add_rule(ConcurrentRunRule('포톤 레이', '홀로그램 그래피티 : 융합'), RuleSet.BASE)
일단은 쿨마다 쓰도록 해두겠습니다.

2020-12-23 23:44 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +        ruleset.add_rule(InactiveRule('홀로그램 그래피티 : 역장', '홀로그램 그래피티 : 융합'), RuleSet.BASE)  # 홀로그램 바뀔 때 같이 수정바람
이건 그냥 시스템적으로 불가능한거라, Constraint로 가는게 맞겠네요.

2020-12-24 00:01 UTC, cheese98 commented on dpmModule/jobs/xenon.py
> +        ruleset.add_rule(InactiveRule('홀로그램 그래피티 : 역장', '홀로그램 그래피티 : 융합'), RuleSet.BASE)  # 홀로그램 바뀔 때 같이 수정바람
확인 후 수정 완료했습니다.

2020-12-25 01:04 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +        ruleset.add_rule(ConcurrentRunRule('메가 스매셔(개시)', '오파츠 코드'), RuleSet.BASE)
이렇게 해도 오파츠 코드 끝자락에 발사 시작해서 중간에 꺼지기도 하던데, 음... 남은 지속시간까지 같이 비교하는게 좋지만, 그러면 스매셔가 지나치게 밀릴 위험이 있고, 그러면 오파츠코드-엑스트라 서플라이-스매셔 순으로 쓰게 강제하거나... 으 어렵네요

2020-12-25 01:09 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +        ruleset.add_rule(ConcurrentRunRule('메가 스매셔(개시)', '오파츠 코드'), RuleSet.BASE)
일단 이 rule은 거의 의미없을거예요. 그냥 빼고 나중에 생각하는게 좋겠네요.

2020-12-25 02:16 UTC, icepeng commented on dpmModule/jobs/xenon.py
> +        Hologram_Fusion_Buff = core.BuffSkill("홀로그램 그래피티 : 융합 (버프)", 0, 30000+10000, pdamage=5+vEhc.getV(4, 4)//2, rem=False).wrap(core.BuffSkillWrapper)
이거도 cooltime=-1 없어서 멜트다운때랑 똑같은 버그가 발생하네요.

2020-12-25 02:17 UTC, merged